# Module: tomcat
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/master/metricbeat-module-tomcat.html

- module: tomcat
  metricsets: ["threading", "cache", "memory", "requests"]
  period: 10s
  hosts: [$tomcat-hosts]
  path: "/jolokia/?ignoreErrors=true&canonicalNaming=false"
