from elasticsearch import Elasticsearch
from plyer import notification
import time

# Password for the 'elastic' user generated by Elasticsearch
ELASTIC_PASSWORD = "ductho"
datastream_name = "logs-system-memory"


def get_latest_records():
    # Thay đổi địa chỉ Elasticsearch, thông tin xác thực, và phiên bản Elasticsearch theo tài khoản của bạn
    es = Elasticsearch(
        "https://localhost:9200",
        ca_certs="D:/Program Files/elasticsearch-8.7.1/config/certs/http_ca.crt",
        basic_auth=("elastic", ELASTIC_PASSWORD),
    )

    # Truy vấn Elasticsearch để lấy 10 kết quả mới nhất
    query = {
        "size": 10,
        "sort": [{"@timestamp": {"order": "desc"}}],
        "query": {"match_all": {}},
    }
    response = es.search(index=datastream_name, body=query)

    # Kiểm tra và xử lý kết quả
    if response["hits"]["hits"]:
        for hit in response["hits"]["hits"]:
            source = hit["_source"]
            # Truy cập các trường bạn muốn từ kết quả
            field_a = source["system"]["memory"]["total"]
            field_b = source["system"]["memory"]["free"]
            # Xử lý kết quả ở đây
            print("Field a: {}, Field b: {}".format(field_a, field_b))
    else:
        print("No records found.")

    # Đóng kết nối Elasticsearch
    es.close()
    notification.notify(title="Elasticsearch Query check", message="123", timeout=10)


# Gọi hàm để lấy 10 kết quả mới nhất
# Lặp lại truy vấn mỗi 10 giây
while True:
    get_latest_records()
    time.sleep(10)
